
package net.ddns.lsmobile.zencashvaadinwalletui4cpp.ui.desktop;

import com.vaadin.annotations.Push;
import com.vaadin.annotations.Theme;
import com.vaadin.server.VaadinRequest;
import com.vaadin.shared.communication.PushMode;
import com.vaadin.shared.ui.ui.Transport;
import com.xdev.res.ApplicationResource;
import com.xdev.security.authentication.ui.XdevAuthenticationNavigator;
import com.xdev.ui.XdevUI;

@Push(value = PushMode.MANUAL, transport = Transport.LONG_POLLING)
@Theme("ZENCashVaadinWalletUI4CPP")
public class DesktopUI extends XdevUI {
	public DesktopUI() {
		super();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public void init(final VaadinRequest request) {
		this.initUI();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.navigator = new XdevAuthenticationNavigator(this, this);
	
		this.setIcon(new ApplicationResource(this.getClass(), "WebContent/WEB-INF/resources/images/zenicon.png"));
		this.setTabIndex(0);
		this.navigator.setRedirectViewName("home");
		this.navigator.addView("", LoginView.class);
		this.navigator.addView("loading", LoadingView.class);
		this.navigator.addView("home", MainView.class);
		this.navigator.addView("signing", SigningView.class);
	
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private XdevAuthenticationNavigator navigator;
	// </generated-code>
}