package net.ddns.lsmobile.zencashvaadinwalletui4cpp.ui.desktop;

import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.CustomComponent;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevView;

public class NotificationView extends XdevView {

	/**
	 * 
	 */
	public NotificationView(final String caption, final String message) {
		super();
		this.initUI();
		
		setCaption(caption);
		this.labelMessage.setValue(message);
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.gridLayout = new XdevGridLayout();
		this.labelMessage = new XdevLabel();
	
		this.labelMessage.setValue("Message");
		this.labelMessage.setContentMode(ContentMode.HTML);
	
		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.labelMessage.setSizeUndefined();
		this.gridLayout.addComponent(this.labelMessage, 0, 0);
		final CustomComponent gridLayout_hSpacer = new CustomComponent();
		gridLayout_hSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_hSpacer, 1, 0, 1, 0);
		this.gridLayout.setColumnExpandRatio(1, 1.0F);
		final CustomComponent gridLayout_vSpacer = new CustomComponent();
		gridLayout_vSpacer.setSizeFull();
		this.gridLayout.addComponent(gridLayout_vSpacer, 0, 1, 0, 1);
		this.gridLayout.setRowExpandRatio(1, 1.0F);
		this.gridLayout.setSizeFull();
		this.setContent(this.gridLayout);
		this.setWidth(640, Unit.PIXELS);
		this.setHeight(200, Unit.PIXELS);
	} // </generated-code>

	// <generated-code name="variables">
	private XdevLabel labelMessage;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
